#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
    ln -s /usr/lib/amjdesk/amjdesk /usr/bin/amjdesk
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/amjdesk.service ]; then
			rm /etc/systemd/system/amjdesk.service /usr/lib/systemd/system/amjdesk.service /usr/lib/systemd/user/amjdesk.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/amjdesk/files/systemd/amjdesk.service /usr/lib/systemd/system/amjdesk.service
		systemctl daemon-reload
		systemctl enable amjdesk
		systemctl start amjdesk
	fi
fi
